"use client";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { Autoplay } from "swiper/modules";
import Image from "next/image";

export const Brands = () => {
  return (
    <Swiper
      slidesPerView={7}
      centeredSlides={true}
      loop={true}
      pagination={{
        clickable: true,
      }}
      autoplay={{
        delay: 2000,
        disableOnInteraction: false,
      }}
      modules={[Autoplay]}
      className="mySwiper flex w-full items-center justify-center mb-8"
    >
      <SwiperSlide>
        <Image
          src={"/sony.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/toshiba.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/versace.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/xiaomi.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/adidas.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/samsung.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/rolex.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/puma.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/pf.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/msi.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/mac.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/lv.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/loreal.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/lg.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/hp.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/gucci.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/dg.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/dior.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/dell.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/bulgari.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/benq.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/asus.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
      <SwiperSlide>
        <Image
          src={"/apple.png"}
          width={150}
          height={150}
          alt=""
          className="h-[75px]"
        />
      </SwiperSlide>
    </Swiper>
  );
};
